// ─── Services ────────────────────────────────────────────────────────────────

export interface Service {
  slug: string;
  name: string;
  shortName: string;
  tagline: string;
  description: string;
  features: string[];
  icon: string;
}

export const services: Service[] = [
  {
    slug: 'business-voip',
    name: 'Business Phone Systems',
    shortName: 'Business Phones',
    tagline: 'AI-ready calling, routing, and messaging for modern teams',
    description:
      'UponAI delivers business calling, intelligent routing, messaging, and remote-ready workflows in one platform so your team stays reachable everywhere customers expect to connect.',
    features: [
      'Unlimited local & long distance calling',
      'Auto-attendant & IVR menus',
      'Call recording & monitoring',
      'Voicemail to email with transcription',
      'Mobile app included',
      'Ring groups & queues',
      'HD voice quality',
      '24/7 US-based support',
    ],
    icon: 'phone',
  },
  {
    slug: 'contact-centers',
    name: 'Contact Center Solutions',
    shortName: 'Contact Centers',
    tagline: 'Omnichannel contact center - voice, SMS, chat & video',
    description:
      'Modern contact centers do much more than power telephone interactions. Connect with your customers over multiple channels including SMS, in-app chat, video, and more - all from one unified platform.',
    features: [
      'Omnichannel routing (voice, SMS, chat, email)',
      'Real-time agent dashboards',
      'CRM integrations',
      'Intelligent call routing & IVR',
      'Call recording & quality scoring',
      'Supervisor monitoring & whisper coaching',
      'Workforce management tools',
      'Custom reporting & analytics',
    ],
    icon: 'headset',
  },
  {
    slug: 'sip-trunks',
    name: 'SIP Trunking',
    shortName: 'SIP Trunks',
    tagline: 'Modernize carrier connectivity while keeping your existing phone setup',
    description:
      'UponAI SIP trunking helps teams reduce carrier complexity, add redundancy, and scale calling capacity without ripping out the hardware or workflows they already rely on.',
    features: [
      'Unlimited concurrent calls',
      'Keep your existing on-prem phone hardware',
      'Local & toll-free DID numbers',
      'E911 emergency services',
      'Failover & redundancy built-in',
      'No contracts required',
      'Per-minute or unlimited pricing',
      'BYOC (Bring Your Own Carrier)',
    ],
    icon: 'server',
  },
  {
    slug: 'hosted-fax',
    name: 'Hosted Fax (Cloud Fax)',
    shortName: 'Hosted Fax',
    tagline: 'Send & receive faxes from any device - no fax machine needed',
    description:
      'Fax remains essential in healthcare, legal, and operations-heavy teams. UponAI cloud fax keeps documents moving securely without physical machines or fragmented workflows.',
    features: [
      'Send & receive faxes by email',
      'Dedicated fax DID numbers',
      'Web portal fax management',
      'HIPAA-compliant transmission',
      'Fax-to-email & email-to-fax',
      'Multiple user accounts',
      'Fax broadcasting capability',
      'API integration available',
    ],
    icon: 'printer',
  },
  {
    slug: 'mobile-voip-sms',
    name: 'Mobile Calling & SMS',
    shortName: 'Mobile Calling & SMS',
    tagline: 'Work from anywhere with your business number on any device',
    description:
      "Today's teams need mobility, fast response times, and a consistent business presence. UponAI keeps your number, messaging, and team availability synced across mobile, desktop, and browser experiences.",
    features: [
      'iOS & Android mobile apps',
      'Business SMS text messaging',
      'Softphone for laptop & desktop',
      'Unified messaging inbox',
      'Keep your business number mobile',
      'Presence & availability status',
      'Group messaging & chat',
      'Push notifications',
    ],
    icon: 'smartphone',
  },
  {
    slug: 'web-video-conferencing',
    name: 'Web & Video Conferencing',
    shortName: 'Video Conferencing',
    tagline: 'HD meetings, screen sharing & webinars - no extra software',
    description:
      'Run meetings, demos, webinars, and internal collaboration sessions from the same communications platform your team already uses for calls and messaging.',
    features: [
      'HD video meetings (up to 500 participants)',
      'Screen sharing & annotation tools',
      'Webinar & virtual event hosting',
      'Meeting recording & transcription',
      'Virtual backgrounds',
      'Breakout rooms',
      'One-click dial-in from your business number',
      'Calendar integrations (Google, Outlook)',
    ],
    icon: 'video',
  },
  {
    slug: 'voip-integration',
    name: 'Integrations & APIs',
    shortName: 'Integrations',
    tagline: 'Connect calling, messaging, and automation to your business stack',
    description:
      'UponAI connects communications with your CRM, help desk, scheduling tools, and internal workflows so every conversation is logged, routed, and acted on automatically.',
    features: [
      'Salesforce, HubSpot & Zoho CRM',
      'Microsoft Teams & Google Workspace',
      'Zapier & Make (formerly Integromat)',
      'REST API & webhooks',
      'Click-to-call from any web page',
      'Screen pop on inbound calls',
      'Call logging to CRM automatically',
      'Custom integration development',
    ],
    icon: 'puzzle',
  },
  {
    slug: 'ai-voice-agents',
    name: 'AI Voice Agents',
    shortName: 'AI Voice Agents',
    tagline: 'Replace your IVR with a human-sounding AI that never sleeps',
    description:
      'Powered by UponAI technology, our AI Voice Agents answer every call with natural conversation - qualifying leads, booking appointments, handling FAQs, and routing callers intelligently without a single hold queue.',
    features: [
      'Human-sounding conversational AI',
      'Replaces outdated touch-tone IVR',
      'Answers calls 24/7/365 - no hold queues',
      'Lead qualification & instant routing',
      'Appointment scheduling via voice',
      'Multi-language & accent support',
      'Seamless handoff to live agents',
      'Full call transcripts & analytics',
    ],
    icon: 'bot',
  },
  {
    slug: 'ai-chatbots',
    name: 'AI Chatbots for Business',
    shortName: 'AI Chatbots',
    tagline: 'Engage, qualify, and convert website visitors automatically',
    description:
      'Powered by UponAI, our AI chatbots deliver personalized support around the clock - answering questions, capturing leads, and routing customers to the right team instantly. No wait times, no missed opportunities.',
    features: [
      'Conversational AI trained on your business',
      'Lead capture & qualification automation',
      'CRM integration & instant data logging',
      'Escalation to live agents on demand',
      'Multi-channel deployment (web, SMS, social)',
      'Custom conversation flows & personas',
      'Real-time analytics & engagement data',
      'HIPAA & compliance-ready options',
    ],
    icon: 'bot',
  },
];

// ─── Industries ───────────────────────────────────────────────────────────────

export interface Industry {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  challenges: string[];
  solutions: string[];
  features: string[];
  stats: { value: string; label: string }[];
  icon: string;
  color: string;
}

export const industries: Industry[] = [
  {
    slug: 'healthcare',
    name: 'Healthcare & Medical',
    tagline: 'HIPAA-ready communications and AI voice workflows for healthcare',
    description:
      'Healthcare organizations need secure communications, dependable routing, and AI-supported patient access that meet strict HIPAA expectations across clinics, hospitals, and multi-location practices.',
    challenges: ['HIPAA compliance for all communications', 'After-hours patient access & on-call routing', 'Multi-location coordination across campuses', 'Integration with EHR/EMR systems', 'Long patient hold times damaging satisfaction'],
    solutions: ['HIPAA-ready calling platform with encrypted communications', 'Secure voicemail and compliant fax workflows', 'Intelligent nurse station and department routing', 'After-hours AI answering with on-call escalation', 'Queue management with patient callback options'],
    features: ['HIPAA Business Associate Agreement (BAA)', 'Secure voicemail-to-email transcription', 'Patient callback & reminder SMS', 'Department-specific auto-attendants', 'E911 per floor/wing routing', 'Call recording with secure storage'],
    stats: [{ value: '100%', label: 'HIPAA Ready' }, { value: '< 30s', label: 'Avg Answer Time' }, { value: '99.99%', label: 'Uptime SLA' }, { value: '24/7', label: 'Patient Coverage' }],
    icon: 'heart',
    color: 'red',
  },
  {
    slug: 'education',
    name: 'Schools & Education',
    tagline: 'Campus-wide communications for K-12 schools, colleges, and universities',
    description:
      'Educational institutions need reliable communications to connect students, staff, parents, and administrators across classrooms, departments, and campuses without adding operational complexity.',
    challenges: ['Campus-wide coverage across multiple buildings', 'Tight budget constraints & annual renewals', 'Emergency notification to all staff & students', 'Connecting remote & in-person staff', 'Aging legacy phone hardware'],
    solutions: ['Scalable campus-wide calling deployment', 'E911 routing per building and floor', 'Auto-attendant coverage for every department', 'Mass SMS notification system', 'Cloud-managed administration with minimal hardware burden'],
    features: ['Per-classroom & office extensions', 'Emergency mass notification via SMS', 'Parent communication lines', 'Virtual extensions for remote staff', 'Voicemail-to-email transcription', 'Education pricing programs'],
    stats: [{ value: '50%', label: 'Cost Savings vs Legacy' }, { value: '2,000+', label: 'Extensions Supported' }, { value: '24/7', label: 'US Support' }, { value: 'Multi-Site', label: 'Campus Ready' }],
    icon: 'graduation-cap',
    color: 'blue',
  },
  {
    slug: 'financial-services',
    name: 'Financial Services',
    tagline: 'Recorded, compliant communications for banks, credit unions, and advisors',
    description:
      'Financial institutions need secure, recorded communications that support compliance, auditability, and consistent client service across branches, advisors, and service teams.',
    challenges: ['SEC/FINRA call recording mandates', 'Client confidentiality & data security', 'Multi-branch call coordination', 'High-volume inbound call management', 'Compliance audit trails'],
    solutions: ['Automatic 100% call recording & 7-year archiving', 'End-to-end encrypted communications', 'Branch-to-branch free internal calling', 'Intelligent queue routing by product line', 'Tamper-proof compliance logs'],
    features: ['MiFID II & FINRA-ready recording', 'Encrypted call & voicemail storage', 'Branch-to-branch free calling', 'CRM screen pop on inbound calls', 'Real-time supervisor monitoring', 'Custom hold music & messaging'],
    stats: [{ value: '100%', label: 'Calls Recorded' }, { value: '7 Yr', label: 'Archive Retention' }, { value: '256-bit', label: 'Encryption' }, { value: 'Audit-Ready', label: 'Compliance Logs' }],
    icon: 'dollar-sign',
    color: 'green',
  },
  {
    slug: 'construction',
    name: 'Construction Companies',
    tagline: 'Mobile-first communications for construction crews and job sites',
    description:
      'Construction teams operate across multiple job sites with crews who are always on the move. UponAI keeps field teams, dispatch, and office staff connected without depending on fixed desk hardware.',
    challenges: ['Mobile workforce scattered across job sites', 'No reliable desk phone infrastructure on-site', 'Subcontractor coordination & communication', 'Project-by-project number management', 'Office-to-field communication delays'],
    solutions: ['Mobile calling app for iOS and Android', 'Virtual extensions per project or crew', 'SMS for instant field updates', 'Call routing to any device or location', 'Temporary numbers per job site'],
    features: ['Mobile softphone for field crews', 'SMS group messaging for crews', 'Temporary project phone numbers', 'Voicemail-to-email while on-site', 'Call forwarding to any number', 'No desk phone hardware needed'],
    stats: [{ value: '100%', label: 'Mobile-Ready' }, { value: '0', label: 'Hardware Required' }, { value: 'Instant', label: 'Setup Per Site' }, { value: 'Field Teams', label: 'Dispatch Connected' }],
    icon: 'hard-hat',
    color: 'yellow',
  },
  {
    slug: 'auto-repair',
    name: 'Auto Repair Shops',
    tagline: 'Customer-call workflows built for auto shops and service bays',
    description:
      'Auto repair shops live and die by phone calls. UponAI helps teams answer every inquiry, confirm appointments, and keep customers updated even during the busiest service windows.',
    challenges: ['Missed calls during peak shop hours', 'No system for customer follow-up calls', 'Lost revenue from unanswered phones', 'No way to send appointment reminders', 'Single phone line creating bottlenecks'],
    solutions: ['Auto-attendant for immediate after-hours pickup', 'Call queue with hold music & estimated wait', 'Voicemail-to-email with instant transcription', 'SMS appointment reminders & status updates', 'Multiple lines from one number'],
    features: ['Auto-attendant 24/7 answering', 'Customer SMS status updates', 'Voicemail-to-email transcription', 'Call recording for quality review', 'Virtual receptionist options', 'Toll-free number included'],
    stats: [{ value: '0', label: 'Missed Calls' }, { value: '24/7', label: 'Auto-Answering' }, { value: '30%', label: 'More Bookings' }, { value: 'Status SMS', label: 'Customer Updates' }],
    icon: 'wrench',
    color: 'orange',
  },
  {
    slug: 'law-firms',
    name: 'Law Firms & Legal',
    tagline: 'Confidential, recorded communications for attorneys and intake teams',
    description:
      'Law firms require confidential, reliable phone communications with the ability to record calls, route clients to specific attorneys, and maintain professional presence across all client interactions.',
    challenges: ['Client confidentiality & attorney-client privilege', 'Accurate call billing by matter/client', 'After-hours urgent client calls', 'Professional auto-attendant image', 'Multi-office coordination'],
    solutions: ['End-to-end encrypted calls', 'Call recording with matter codes', 'Attorney-specific direct lines', 'After-hours emergency call routing', 'Unified multi-office phone system'],
    features: ['Attorney direct-dial extensions', 'Encrypted call recording & storage', 'Client intake call routing', 'After-hours emergency escalation', 'Voicemail-to-email transcription', 'Conference bridge for depositions'],
    stats: [{ value: '100%', label: 'Encrypted Calls' }, { value: '< 2s', label: 'Ring Time' }, { value: '99.99%', label: 'Uptime' }, { value: 'Intake-Ready', label: 'Client Routing' }],
    icon: 'scale',
    color: 'slate',
  },
  {
    slug: 'churches',
    name: 'Churches & Non-Profits',
    tagline: 'Flexible communications for churches, ministries, and non-profit teams',
    description:
      'Churches and non-profit organizations need dependable communications that help small teams, volunteers, and multi-campus operations stay organized without adding technical overhead.',
    challenges: ['Extremely tight budgets', 'Volunteer staff coordination', 'Multi-campus or multi-site communication', 'Seasonal event surge in call volume', 'Lack of dedicated IT staff'],
    solutions: ['Non-profit & faith-based pricing programs', 'Multi-campus unified phone system', 'Auto-attendant for service times & events', 'SMS mass notifications to congregation', 'Simple self-managed administration'],
    features: ['Non-profit discount pricing', 'Multi-campus call routing', 'Event hotline setup', 'SMS prayer chain & notifications', 'Volunteer coordinator extensions', 'Easy self-service admin portal'],
    stats: [{ value: '40%', label: 'Budget Efficiency' }, { value: 'Unlimited', label: 'Extensions' }, { value: 'No', label: 'IT Staff Needed' }, { value: 'Multi-Campus', label: 'Ready' }],
    icon: 'church',
    color: 'purple',
  },
  {
    slug: 'advertising',
    name: 'Advertising & Marketing',
    tagline: 'Call tracking, attribution, and analytics for marketing agencies',
    description:
      'Advertising and marketing agencies need call tracking, attribution, and dynamic number management to prove campaign ROI and keep client reporting sharp.',
    challenges: ['Attributing inbound calls to campaigns', 'Proving ROI to clients', 'Managing numbers for multiple clients', 'Tracking which ads drive the most calls', 'Agency-wide call quality control'],
    solutions: ['Dynamic number insertion (DNI) per campaign', 'Campaign-level call analytics & dashboards', 'Per-client number pools & reporting', 'Call recording for quality review', 'White-label client reporting portal'],
    features: ['Dynamic number insertion (DNI)', 'Campaign attribution reports', 'Per-client billing & reporting', 'Call recording & scoring', 'Keyword-level call tracking', 'API & webhook integrations'],
    stats: [{ value: '100%', label: 'Call Attribution' }, { value: 'Real-time', label: 'Analytics' }, { value: 'Unlimited', label: 'Tracking Numbers' }, { value: 'Client-Ready', label: 'Reporting' }],
    icon: 'megaphone',
    color: 'pink',
  },
  {
    slug: 'insurance',
    name: 'Insurance Agencies',
    tagline: 'High-volume inbound communications for insurance teams',
    description:
      'Insurance agencies handle high volumes of inbound leads and service calls. UponAI helps agencies route conversations intelligently, capture after-hours demand, and keep policyholders moving.',
    challenges: ['High inbound lead call volume', 'Speed-to-lead response time', 'Compliance call recording requirements', 'Agent performance & quality monitoring', 'After-hours lead capture'],
    solutions: ['Intelligent call queuing & priority routing', 'Automatic CRM contact creation', 'Mandatory compliance call recording', 'Real-time agent dashboards & whisper coaching', 'AI after-hours lead capture'],
    features: ['Priority lead routing by line of business', 'CRM integration (Salesforce, HubSpot)', 'Compliance call recording & archiving', 'Agent whisper coaching', 'Real-time performance dashboards', 'After-hours AI answering'],
    stats: [{ value: '< 3s', label: 'Lead Response' }, { value: '100%', label: 'Calls Recorded' }, { value: '40%', label: 'More Conversions' }, { value: 'After-Hours', label: 'Lead Capture' }],
    icon: 'shield',
    color: 'blue',
  },
  {
    slug: 'real-estate',
    name: 'Real Estate Agencies',
    tagline: 'Never miss a property inquiry with AI-ready real estate communications',
    description:
      'Real estate agents live on their phones. UponAI keeps agents reachable from any device, routes property inquiries to the right person, and captures every lead whether the team is in the office or on showings.',
    challenges: ['Agents always on the go, hard to reach', 'Missed property inquiry calls losing deals', 'No unified system across a brokerage', 'Tracking which listings generate calls', 'Client follow-up coordination'],
    solutions: ['Mobile calling from any device', 'Property-specific tracking numbers', 'Agent-to-agent instant transfer', 'Voicemail-to-email for fast follow-up', 'CRM integration for lead capture'],
    features: ['Mobile app for iOS & Android', 'Listing-specific phone numbers', 'Agent availability & presence status', 'Click-to-call from MLS listings', 'Team call queues by market area', 'CRM auto-logging of all calls'],
    stats: [{ value: '0', label: 'Missed Inquiries' }, { value: '24/7', label: 'Reachable' }, { value: '3x', label: 'Faster Follow-up' }, { value: 'Lead Capture', label: 'Always On' }],
    icon: 'home',
    color: 'green',
  },
  {
    slug: 'restaurants',
    name: 'Restaurants & Food Service',
    tagline: 'More reservations and fewer missed calls for restaurants',
    description:
      'Restaurants cannot afford to miss calls during the dinner rush. UponAI helps teams handle reservation demand, answer common questions, and protect the in-house dining experience during peak service.',
    challenges: ['Calls missed during peak service hours', 'Staff answering phones instead of serving tables', 'No reservation confirmation system', 'Managing calls across multiple locations', 'Holiday & event call surges'],
    solutions: ['Auto-attendant handles calls during rush', 'SMS reservation confirmations & reminders', 'On-hold messaging with daily specials', 'Multi-location unified management', 'Overflow routing during busy periods'],
    features: ['Auto-attendant with hours & reservations menu', 'SMS reservation confirmations', 'On-hold custom messaging & music', 'Online ordering call integration', 'Multi-location management', 'Holiday routing presets'],
    stats: [{ value: '0', label: 'Missed Rush Calls' }, { value: '25%', label: 'More Reservations' }, { value: 'SMS', label: 'Confirmations' }, { value: 'Peak Hours', label: 'Overflow Ready' }],
    icon: 'utensils',
    color: 'orange',
  },
  {
    slug: 'hotels-hospitality',
    name: 'Hotels & Hospitality',
    tagline: 'Guest-ready communications for hotels, motels, and resorts',
    description:
      'Hotels need communications that support the guest experience from booking to checkout. UponAI helps properties manage front-desk demand, room-service inquiries, and internal routing smoothly.',
    challenges: ['In-room guest phone infrastructure costs', 'Front desk overwhelmed with calls', 'Coordinating housekeeping & maintenance calls', 'Integration with property management systems', 'Guest satisfaction scores tied to communication'],
    solutions: ['In-room calling options with modern management', 'Front desk smart queue and routing', 'Department-to-department extension dialing', 'PMS system integration', 'Guest callback and wake-up call automation'],
    features: ['In-room phone system support', 'Wake-up call automation', 'PMS integration (Opera, Cloudbeds)', 'Department extensions (housekeeping, valet)', 'Guest voicemail', 'Auto-attendant in multiple languages'],
    stats: [{ value: '60%', label: 'Cost vs Legacy' }, { value: 'PMS', label: 'Integration Ready' }, { value: '24/7', label: 'Guest Service' }, { value: 'Multi-Language', label: 'Front Desk Support' }],
    icon: 'hotel',
    color: 'amber',
  },
  {
    slug: 'retail',
    name: 'Retail & E-Commerce',
    tagline: 'Customer service communications that scale with retail demand',
    description:
      'Retail businesses need professional communications that handle customer inquiries, order status calls, and returns without building a full call center from scratch.',
    challenges: ['High call volume during promotions & holidays', 'Customer service staff shortage', 'Order status & tracking inquiry overload', 'Multi-store communication', 'Customer satisfaction at stake'],
    solutions: ['Scalable call queues for seasonal surges', 'AI auto-attendant for order status FAQs', 'Store-to-store instant transfer', 'SMS for shipping notifications', 'CRM integration for customer history'],
    features: ['Scalable call queuing', 'AI FAQ answering', 'Store-to-store extensions', 'SMS order notifications', 'Call recording for training', 'Seasonal routing presets'],
    stats: [{ value: '40%', label: 'Fewer Hold Calls' }, { value: 'Scales', label: 'During Peak Season' }, { value: 'SMS', label: 'Order Updates' }, { value: 'AI FAQ', label: 'Ready' }],
    icon: 'shopping-bag',
    color: 'purple',
  },
  {
    slug: 'property-management',
    name: 'Property Management',
    tagline: 'Streamline tenant and maintenance communications across every property',
    description:
      'Property management companies juggle tenant calls, maintenance requests, and vendor coordination daily. UponAI keeps every inquiry routed correctly and every property team more responsive.',
    challenges: ['After-hours emergency maintenance calls', 'Tenant call routing to right property manager', 'Vendor & contractor coordination', 'Multiple property number management', 'Maintenance request tracking'],
    solutions: ['24/7 emergency maintenance hotline routing', 'Property-specific direct numbers', 'On-call escalation for emergencies', 'SMS for maintenance updates', 'Multi-property management from one platform'],
    features: ['Per-property phone numbers', 'Emergency on-call routing', 'Tenant maintenance SMS updates', 'Vendor directory extensions', 'Call recording for dispute resolution', 'Multi-property admin portal'],
    stats: [{ value: '24/7', label: 'Emergency Line' }, { value: 'Unlimited', label: 'Properties' }, { value: 'SMS', label: 'Tenant Updates' }, { value: 'On-Call', label: 'Escalation Ready' }],
    icon: 'building',
    color: 'slate',
  },
  {
    slug: 'home-services',
    name: 'Home Services & HVAC',
    tagline: 'AI-ready communications for plumbers, electricians, HVAC techs, and contractors',
    description:
      'Home service businesses run on inbound calls. UponAI helps capture every service request, dispatch efficiently, and keep homeowners informed so more jobs turn into revenue.',
    challenges: ['Missing calls while techs are on job sites', 'Inefficient dispatcher-to-tech communication', 'No call tracking for marketing ROI', 'After-hours emergency call management', 'Scheduling coordination chaos'],
    solutions: ['Mobile calling app for field technicians', 'Dispatcher call queue and routing', 'Marketing call tracking numbers', 'After-hours emergency answering', 'SMS job status updates to customers'],
    features: ['Mobile app for field techs', 'Dispatcher call routing dashboard', 'Marketing tracking numbers', 'After-hours emergency auto-attendant', 'Customer SMS job updates', 'GPS-based nearest tech routing'],
    stats: [{ value: '0', label: 'Missed Service Calls' }, { value: 'Mobile', label: 'Tech App Included' }, { value: '20%', label: 'More Jobs Booked' }, { value: 'After-Hours', label: 'Coverage' }],
    icon: 'tool',
    color: 'yellow',
  },
  {
    slug: 'dental',
    name: 'Dental Offices',
    tagline: 'HIPAA-ready communications built for dental practices',
    description:
      'Dental practices need reliable, HIPAA-ready communications that handle appointment scheduling, insurance verification, and patient reminders without disrupting the clinical environment.',
    challenges: ['HIPAA compliance for patient communications', 'High appointment scheduling call volume', 'Patient no-shows & cancellations', 'Insurance verification call coordination', 'After-hours answering for emergencies'],
    solutions: ['HIPAA-compliant cloud phone with BAA', 'Appointment SMS reminders to reduce no-shows', 'Smart queue for scheduling calls', 'Insurance line with hold messaging', 'After-hours emergency routing'],
    features: ['HIPAA Business Associate Agreement', 'Appointment reminder SMS', 'Insurance verification hold messaging', 'Hygienist & doctor direct extensions', 'Patient recall campaign SMS', 'Secure voicemail-to-email'],
    stats: [{ value: '100%', label: 'HIPAA Ready' }, { value: '40%', label: 'Fewer No-Shows' }, { value: 'SMS', label: 'Reminders Included' }, { value: 'Recall', label: 'Campaign Ready' }],
    icon: 'tooth',
    color: 'cyan',
  },
  {
    slug: 'logistics',
    name: 'Logistics & Transportation',
    tagline: 'Keep drivers, dispatchers, and customers connected in real time',
    description:
      'Logistics and transportation companies need seamless communication between dispatchers, drivers, and customers. UponAI keeps routes, delivery updates, and escalation workflows moving in real time.',
    challenges: ['Driver communication across routes', 'Dispatcher coordination with multiple drivers', 'Real-time customer delivery updates', 'Fleet management communication', 'Compliance call recording'],
    solutions: ['Mobile calling for drivers on any device', 'Dispatcher call board and queue', 'Customer SMS delivery notifications', 'Fleet-wide conference calling', 'Compliance call recording and archiving'],
    features: ['Driver mobile app', 'Dispatcher routing board', 'Customer delivery SMS updates', 'Conference bridge for fleet calls', 'GPS-aware call routing', 'Compliance call recording'],
    stats: [{ value: 'Mobile', label: 'Driver App' }, { value: 'SMS', label: 'Delivery Updates' }, { value: '100%', label: 'Calls Recorded' }, { value: 'Dispatch', label: 'Queue Ready' }],
    icon: 'truck',
    color: 'orange',
  },
  {
    slug: 'technology',
    name: 'Technology Companies',
    tagline: 'API-first communications for technology teams that move fast',
    description:
      'Technology companies need a communications platform that integrates with their stack, scales instantly, and provides the analytics needed to optimize sales and support operations.',
    challenges: ['Integrating phone with existing tech stack', 'Scaling with rapid headcount growth', 'Remote & distributed team communication', 'Sales & support call analytics', 'Developer API access'],
    solutions: ['REST API & webhook-driven integrations', 'Instant seat provisioning at scale', 'Remote-first softphone & mobile app', 'Advanced analytics & call intelligence', 'Full developer documentation & sandbox'],
    features: ['REST API & webhooks', 'Salesforce & HubSpot integration', 'Slack & Teams integration', 'Remote softphone & mobile app', 'Real-time call analytics', 'Developer sandbox access'],
    stats: [{ value: 'API', label: 'First Platform' }, { value: 'Instant', label: 'Seat Provisioning' }, { value: '100+', label: 'Integrations' }, { value: 'Sandbox', label: 'Developer Ready' }],
    icon: 'code',
    color: 'violet',
  },
  {
    slug: 'senior-living',
    name: 'Senior Living & Care Facilities',
    tagline: 'Resident-friendly communications for assisted living and care facilities',
    description:
      'Senior living communities and care facilities need simple, reliable communications for residents, staff coordination, and family updates with accessibility and compliance in mind.',
    challenges: ['Resident accessibility & ease of use', 'HIPAA compliance for medical staff calls', 'Family communication updates', 'Staff-to-staff coordination across wings', 'Emergency call handling'],
    solutions: ['Large-button resident phone options', 'HIPAA-compliant staff communications', 'Family notification via SMS', 'Wing-to-wing extension dialing', 'Emergency call escalation routing'],
    features: ['Large-button resident phones', 'HIPAA Business Associate Agreement', 'Family SMS notification system', 'Wing & unit extensions', 'Emergency escalation routing', 'Nurse station call management'],
    stats: [{ value: '100%', label: 'HIPAA Ready' }, { value: 'Simple', label: 'Resident Interface' }, { value: 'SMS', label: 'Family Updates' }, { value: 'Emergency', label: 'Escalation Ready' }],
    icon: 'heart',
    color: 'rose',
  },
  {
    slug: 'mortgage',
    name: 'Mortgage & Lending',
    tagline: 'High-speed lead response communications for mortgage brokers and lenders',
    description:
      'In mortgage lending, the first lender to call a lead often wins the deal. UponAI gives loan officers instant lead routing, compliant recording, and CRM-connected workflows to close more loans faster.',
    challenges: ['Speed-to-lead response is everything', 'RESPA & regulatory compliance recording', 'Loan officer availability & routing', 'High volume of inbound refinance inquiries', 'CRM integration for pipeline tracking'],
    solutions: ['Instant lead-to-officer routing', 'Compliance call recording with 7-year archive', 'Availability-based intelligent routing', 'Scalable call queues for refinance booms', 'Salesforce & Encompass CRM integration'],
    features: ['Instant lead routing to available LO', 'Compliance recording & archiving', 'CRM auto-logging', 'Loan officer direct lines', 'NMLS compliance support', 'Real-time pipeline call analytics'],
    stats: [{ value: '< 5s', label: 'Lead Response' }, { value: '100%', label: 'Calls Recorded' }, { value: '3x', label: 'More Closed Loans' }, { value: 'CRM', label: 'Pipeline Synced' }],
    icon: 'dollar-sign',
    color: 'emerald',
  },
  {
    slug: 'government',
    name: 'Government & Municipal',
    tagline: 'Reliable, secure communications for government agencies and municipalities',
    description:
      'Government agencies and municipal offices require highly reliable, secure communications with E911 compliance, ADA accessibility, and the ability to handle constituent surges during emergencies.',
    challenges: ['E911 compliance & location accuracy', 'High constituent call volume', 'ADA accessibility requirements', 'Security & government data standards', 'Budget approval & procurement cycles'],
    solutions: ['E911 with per-extension location accuracy', 'Scalable call queues for constituent services', 'ADA-compliant accessibility features', 'FedRAMP-aligned security infrastructure', 'Competitive government contract pricing'],
    features: ['E911 compliance per desk/floor', 'Mass notification system', 'ADA-compliant handsets available', 'Encrypted government-grade communications', 'Multi-department routing', 'Disaster recovery & failover'],
    stats: [{ value: '99.999%', label: 'Uptime SLA' }, { value: 'E911', label: 'Compliant' }, { value: 'ADA', label: 'Accessible' }, { value: 'Disaster', label: 'Recovery Ready' }],
    icon: 'building',
    color: 'blue',
  },
  {
    slug: 'fitness',
    name: 'Fitness & Wellness',
    tagline: 'Communications for gyms, studios, and wellness centers that keep members connected',
    description:
      'Fitness studios and wellness centers need professional communications that handle membership inquiries, class bookings, and client follow-up without a full-time receptionist.',
    challenges: ['Front desk overwhelmed with membership calls', 'Class booking & cancellation management', 'Trainer-to-member follow-up', 'Multi-location franchise coordination', 'Membership renewal reminders'],
    solutions: ['Auto-attendant for hours, classes & pricing', 'SMS class reminders & booking confirmations', 'Trainer direct extensions', 'Multi-location unified management', 'Membership renewal SMS campaigns'],
    features: ['Auto-attendant for bookings & FAQs', 'SMS class & appointment reminders', 'Trainer extension lines', 'Multi-location management', 'Membership SMS renewal campaigns', 'Voicemail-to-email for fast follow-up'],
    stats: [{ value: '30%', label: 'More Bookings' }, { value: 'SMS', label: 'Reminders Included' }, { value: '0', label: 'Missed Inquiries' }, { value: 'Renewals', label: 'Campaign Ready' }],
    icon: 'activity',
    color: 'green',
  },
];

// ─── Cities ────────────────────────────────────────────────────────────────────

export interface City {
  slug: string;
  name: string;
  state: string;
  stateAbbr: string;
  population?: string;
}

export const cities: City[] = [
  // New York / Northeast
  { slug: 'new-york-ny', name: 'New York', state: 'New York', stateAbbr: 'NY', population: '8.3M' },
  { slug: 'brooklyn-ny', name: 'Brooklyn', state: 'New York', stateAbbr: 'NY' },
  { slug: 'queens-ny', name: 'Queens', state: 'New York', stateAbbr: 'NY' },
  { slug: 'bronx-ny', name: 'Bronx', state: 'New York', stateAbbr: 'NY' },
  { slug: 'staten-island-ny', name: 'Staten Island', state: 'New York', stateAbbr: 'NY' },
  { slug: 'yonkers-ny', name: 'Yonkers', state: 'New York', stateAbbr: 'NY' },
  { slug: 'buffalo-ny', name: 'Buffalo', state: 'New York', stateAbbr: 'NY' },
  { slug: 'rochester-ny', name: 'Rochester', state: 'New York', stateAbbr: 'NY' },
  { slug: 'albany-ny', name: 'Albany', state: 'New York', stateAbbr: 'NY' },
  { slug: 'syracuse-ny', name: 'Syracuse', state: 'New York', stateAbbr: 'NY' },
  { slug: 'newark-nj', name: 'Newark', state: 'New Jersey', stateAbbr: 'NJ' },
  { slug: 'jersey-city-nj', name: 'Jersey City', state: 'New Jersey', stateAbbr: 'NJ' },
  { slug: 'paterson-nj', name: 'Paterson', state: 'New Jersey', stateAbbr: 'NJ' },
  { slug: 'elizabeth-nj', name: 'Elizabeth', state: 'New Jersey', stateAbbr: 'NJ' },
  { slug: 'trenton-nj', name: 'Trenton', state: 'New Jersey', stateAbbr: 'NJ' },
  { slug: 'camden-nj', name: 'Camden', state: 'New Jersey', stateAbbr: 'NJ' },
  { slug: 'philadelphia-pa', name: 'Philadelphia', state: 'Pennsylvania', stateAbbr: 'PA', population: '1.6M' },
  { slug: 'pittsburgh-pa', name: 'Pittsburgh', state: 'Pennsylvania', stateAbbr: 'PA' },
  { slug: 'allentown-pa', name: 'Allentown', state: 'Pennsylvania', stateAbbr: 'PA' },
  { slug: 'erie-pa', name: 'Erie', state: 'Pennsylvania', stateAbbr: 'PA' },
  { slug: 'reading-pa', name: 'Reading', state: 'Pennsylvania', stateAbbr: 'PA' },
  { slug: 'scranton-pa', name: 'Scranton', state: 'Pennsylvania', stateAbbr: 'PA' },
  { slug: 'boston-ma', name: 'Boston', state: 'Massachusetts', stateAbbr: 'MA', population: '675K' },
  { slug: 'worcester-ma', name: 'Worcester', state: 'Massachusetts', stateAbbr: 'MA' },
  { slug: 'springfield-ma', name: 'Springfield', state: 'Massachusetts', stateAbbr: 'MA' },
  { slug: 'lowell-ma', name: 'Lowell', state: 'Massachusetts', stateAbbr: 'MA' },
  { slug: 'cambridge-ma', name: 'Cambridge', state: 'Massachusetts', stateAbbr: 'MA' },
  { slug: 'hartford-ct', name: 'Hartford', state: 'Connecticut', stateAbbr: 'CT' },
  { slug: 'new-haven-ct', name: 'New Haven', state: 'Connecticut', stateAbbr: 'CT' },
  { slug: 'bridgeport-ct', name: 'Bridgeport', state: 'Connecticut', stateAbbr: 'CT' },
  { slug: 'stamford-ct', name: 'Stamford', state: 'Connecticut', stateAbbr: 'CT' },
  { slug: 'providence-ri', name: 'Providence', state: 'Rhode Island', stateAbbr: 'RI' },
  { slug: 'manchester-nh', name: 'Manchester', state: 'New Hampshire', stateAbbr: 'NH' },
  { slug: 'portland-me', name: 'Portland', state: 'Maine', stateAbbr: 'ME' },
  { slug: 'burlington-vt', name: 'Burlington', state: 'Vermont', stateAbbr: 'VT' },
  // Mid-Atlantic
  { slug: 'baltimore-md', name: 'Baltimore', state: 'Maryland', stateAbbr: 'MD', population: '585K' },
  { slug: 'washington-dc', name: 'Washington', state: 'District of Columbia', stateAbbr: 'DC', population: '705K' },
  { slug: 'silver-spring-md', name: 'Silver Spring', state: 'Maryland', stateAbbr: 'MD' },
  { slug: 'rockville-md', name: 'Rockville', state: 'Maryland', stateAbbr: 'MD' },
  { slug: 'virginia-beach-va', name: 'Virginia Beach', state: 'Virginia', stateAbbr: 'VA' },
  { slug: 'richmond-va', name: 'Richmond', state: 'Virginia', stateAbbr: 'VA' },
  { slug: 'norfolk-va', name: 'Norfolk', state: 'Virginia', stateAbbr: 'VA' },
  { slug: 'arlington-va', name: 'Arlington', state: 'Virginia', stateAbbr: 'VA' },
  { slug: 'chesapeake-va', name: 'Chesapeake', state: 'Virginia', stateAbbr: 'VA' },
  { slug: 'roanoke-va', name: 'Roanoke', state: 'Virginia', stateAbbr: 'VA' },
  { slug: 'wilmington-de', name: 'Wilmington', state: 'Delaware', stateAbbr: 'DE' },
  // Southeast
  { slug: 'atlanta-ga', name: 'Atlanta', state: 'Georgia', stateAbbr: 'GA', population: '498K' },
  { slug: 'augusta-ga', name: 'Augusta', state: 'Georgia', stateAbbr: 'GA' },
  { slug: 'savannah-ga', name: 'Savannah', state: 'Georgia', stateAbbr: 'GA' },
  { slug: 'columbus-ga', name: 'Columbus', state: 'Georgia', stateAbbr: 'GA' },
  { slug: 'miami-fl', name: 'Miami', state: 'Florida', stateAbbr: 'FL', population: '442K' },
  { slug: 'orlando-fl', name: 'Orlando', state: 'Florida', stateAbbr: 'FL', population: '307K' },
  { slug: 'tampa-fl', name: 'Tampa', state: 'Florida', stateAbbr: 'FL', population: '385K' },
  { slug: 'jacksonville-fl', name: 'Jacksonville', state: 'Florida', stateAbbr: 'FL', population: '949K' },
  { slug: 'west-palm-beach-fl', name: 'West Palm Beach', state: 'Florida', stateAbbr: 'FL' },
  { slug: 'fort-lauderdale-fl', name: 'Fort Lauderdale', state: 'Florida', stateAbbr: 'FL' },
  { slug: 'st-petersburg-fl', name: 'St. Petersburg', state: 'Florida', stateAbbr: 'FL' },
  { slug: 'hialeah-fl', name: 'Hialeah', state: 'Florida', stateAbbr: 'FL' },
  { slug: 'tallahassee-fl', name: 'Tallahassee', state: 'Florida', stateAbbr: 'FL' },
  { slug: 'cape-coral-fl', name: 'Cape Coral', state: 'Florida', stateAbbr: 'FL' },
  { slug: 'fort-myers-fl', name: 'Fort Myers', state: 'Florida', stateAbbr: 'FL' },
  { slug: 'gainesville-fl', name: 'Gainesville', state: 'Florida', stateAbbr: 'FL' },
  { slug: 'pensacola-fl', name: 'Pensacola', state: 'Florida', stateAbbr: 'FL' },
  { slug: 'charlotte-nc', name: 'Charlotte', state: 'North Carolina', stateAbbr: 'NC', population: '874K' },
  { slug: 'raleigh-nc', name: 'Raleigh', state: 'North Carolina', stateAbbr: 'NC', population: '467K' },
  { slug: 'greensboro-nc', name: 'Greensboro', state: 'North Carolina', stateAbbr: 'NC' },
  { slug: 'durham-nc', name: 'Durham', state: 'North Carolina', stateAbbr: 'NC' },
  { slug: 'winston-salem-nc', name: 'Winston-Salem', state: 'North Carolina', stateAbbr: 'NC' },
  { slug: 'fayetteville-nc', name: 'Fayetteville', state: 'North Carolina', stateAbbr: 'NC' },
  { slug: 'nashville-tn', name: 'Nashville', state: 'Tennessee', stateAbbr: 'TN', population: '689K' },
  { slug: 'memphis-tn', name: 'Memphis', state: 'Tennessee', stateAbbr: 'TN' },
  { slug: 'knoxville-tn', name: 'Knoxville', state: 'Tennessee', stateAbbr: 'TN' },
  { slug: 'chattanooga-tn', name: 'Chattanooga', state: 'Tennessee', stateAbbr: 'TN' },
  { slug: 'clarksville-tn', name: 'Clarksville', state: 'Tennessee', stateAbbr: 'TN' },
  { slug: 'louisville-ky', name: 'Louisville', state: 'Kentucky', stateAbbr: 'KY' },
  { slug: 'lexington-ky', name: 'Lexington', state: 'Kentucky', stateAbbr: 'KY' },
  { slug: 'bowling-green-ky', name: 'Bowling Green', state: 'Kentucky', stateAbbr: 'KY' },
  { slug: 'birmingham-al', name: 'Birmingham', state: 'Alabama', stateAbbr: 'AL' },
  { slug: 'montgomery-al', name: 'Montgomery', state: 'Alabama', stateAbbr: 'AL' },
  { slug: 'huntsville-al', name: 'Huntsville', state: 'Alabama', stateAbbr: 'AL' },
  { slug: 'mobile-al', name: 'Mobile', state: 'Alabama', stateAbbr: 'AL' },
  { slug: 'new-orleans-la', name: 'New Orleans', state: 'Louisiana', stateAbbr: 'LA' },
  { slug: 'baton-rouge-la', name: 'Baton Rouge', state: 'Louisiana', stateAbbr: 'LA' },
  { slug: 'shreveport-la', name: 'Shreveport', state: 'Louisiana', stateAbbr: 'LA' },
  { slug: 'lafayette-la', name: 'Lafayette', state: 'Louisiana', stateAbbr: 'LA' },
  { slug: 'columbia-sc', name: 'Columbia', state: 'South Carolina', stateAbbr: 'SC' },
  { slug: 'charleston-sc', name: 'Charleston', state: 'South Carolina', stateAbbr: 'SC' },
  { slug: 'greenville-sc', name: 'Greenville', state: 'South Carolina', stateAbbr: 'SC' },
  { slug: 'jackson-ms', name: 'Jackson', state: 'Mississippi', stateAbbr: 'MS' },
  { slug: 'gulfport-ms', name: 'Gulfport', state: 'Mississippi', stateAbbr: 'MS' },
  { slug: 'little-rock-ar', name: 'Little Rock', state: 'Arkansas', stateAbbr: 'AR' },
  { slug: 'fayetteville-ar', name: 'Fayetteville', state: 'Arkansas', stateAbbr: 'AR' },
  { slug: 'charleston-wv', name: 'Charleston', state: 'West Virginia', stateAbbr: 'WV' },
  // Midwest
  { slug: 'chicago-il', name: 'Chicago', state: 'Illinois', stateAbbr: 'IL', population: '2.7M' },
  { slug: 'aurora-il', name: 'Aurora', state: 'Illinois', stateAbbr: 'IL' },
  { slug: 'rockford-il', name: 'Rockford', state: 'Illinois', stateAbbr: 'IL' },
  { slug: 'joliet-il', name: 'Joliet', state: 'Illinois', stateAbbr: 'IL' },
  { slug: 'naperville-il', name: 'Naperville', state: 'Illinois', stateAbbr: 'IL' },
  { slug: 'springfield-il', name: 'Springfield', state: 'Illinois', stateAbbr: 'IL' },
  { slug: 'peoria-il', name: 'Peoria', state: 'Illinois', stateAbbr: 'IL' },
  { slug: 'detroit-mi', name: 'Detroit', state: 'Michigan', stateAbbr: 'MI', population: '632K' },
  { slug: 'grand-rapids-mi', name: 'Grand Rapids', state: 'Michigan', stateAbbr: 'MI' },
  { slug: 'warren-mi', name: 'Warren', state: 'Michigan', stateAbbr: 'MI' },
  { slug: 'sterling-heights-mi', name: 'Sterling Heights', state: 'Michigan', stateAbbr: 'MI' },
  { slug: 'ann-arbor-mi', name: 'Ann Arbor', state: 'Michigan', stateAbbr: 'MI' },
  { slug: 'lansing-mi', name: 'Lansing', state: 'Michigan', stateAbbr: 'MI' },
  { slug: 'flint-mi', name: 'Flint', state: 'Michigan', stateAbbr: 'MI' },
  { slug: 'columbus-oh', name: 'Columbus', state: 'Ohio', stateAbbr: 'OH', population: '905K' },
  { slug: 'cleveland-oh', name: 'Cleveland', state: 'Ohio', stateAbbr: 'OH' },
  { slug: 'cincinnati-oh', name: 'Cincinnati', state: 'Ohio', stateAbbr: 'OH' },
  { slug: 'toledo-oh', name: 'Toledo', state: 'Ohio', stateAbbr: 'OH' },
  { slug: 'akron-oh', name: 'Akron', state: 'Ohio', stateAbbr: 'OH' },
  { slug: 'dayton-oh', name: 'Dayton', state: 'Ohio', stateAbbr: 'OH' },
  { slug: 'youngstown-oh', name: 'Youngstown', state: 'Ohio', stateAbbr: 'OH' },
  { slug: 'indianapolis-in', name: 'Indianapolis', state: 'Indiana', stateAbbr: 'IN', population: '876K' },
  { slug: 'fort-wayne-in', name: 'Fort Wayne', state: 'Indiana', stateAbbr: 'IN' },
  { slug: 'evansville-in', name: 'Evansville', state: 'Indiana', stateAbbr: 'IN' },
  { slug: 'south-bend-in', name: 'South Bend', state: 'Indiana', stateAbbr: 'IN' },
  { slug: 'milwaukee-wi', name: 'Milwaukee', state: 'Wisconsin', stateAbbr: 'WI' },
  { slug: 'madison-wi', name: 'Madison', state: 'Wisconsin', stateAbbr: 'WI' },
  { slug: 'green-bay-wi', name: 'Green Bay', state: 'Wisconsin', stateAbbr: 'WI' },
  { slug: 'kenosha-wi', name: 'Kenosha', state: 'Wisconsin', stateAbbr: 'WI' },
  { slug: 'minneapolis-mn', name: 'Minneapolis', state: 'Minnesota', stateAbbr: 'MN', population: '429K' },
  { slug: 'st-paul-mn', name: 'St. Paul', state: 'Minnesota', stateAbbr: 'MN' },
  { slug: 'rochester-mn', name: 'Rochester', state: 'Minnesota', stateAbbr: 'MN' },
  { slug: 'duluth-mn', name: 'Duluth', state: 'Minnesota', stateAbbr: 'MN' },
  { slug: 'st-louis-mo', name: 'St. Louis', state: 'Missouri', stateAbbr: 'MO', population: '301K' },
  { slug: 'kansas-city-mo', name: 'Kansas City', state: 'Missouri', stateAbbr: 'MO', population: '508K' },
  { slug: 'springfield-mo', name: 'Springfield', state: 'Missouri', stateAbbr: 'MO' },
  { slug: 'columbia-mo', name: 'Columbia', state: 'Missouri', stateAbbr: 'MO' },
  { slug: 'omaha-ne', name: 'Omaha', state: 'Nebraska', stateAbbr: 'NE' },
  { slug: 'lincoln-ne', name: 'Lincoln', state: 'Nebraska', stateAbbr: 'NE' },
  { slug: 'des-moines-ia', name: 'Des Moines', state: 'Iowa', stateAbbr: 'IA' },
  { slug: 'cedar-rapids-ia', name: 'Cedar Rapids', state: 'Iowa', stateAbbr: 'IA' },
  { slug: 'davenport-ia', name: 'Davenport', state: 'Iowa', stateAbbr: 'IA' },
  { slug: 'sioux-falls-sd', name: 'Sioux Falls', state: 'South Dakota', stateAbbr: 'SD' },
  { slug: 'rapid-city-sd', name: 'Rapid City', state: 'South Dakota', stateAbbr: 'SD' },
  { slug: 'fargo-nd', name: 'Fargo', state: 'North Dakota', stateAbbr: 'ND' },
  { slug: 'bismarck-nd', name: 'Bismarck', state: 'North Dakota', stateAbbr: 'ND' },
  { slug: 'billings-mt', name: 'Billings', state: 'Montana', stateAbbr: 'MT' },
  { slug: 'missoula-mt', name: 'Missoula', state: 'Montana', stateAbbr: 'MT' },
  { slug: 'wichita-ks', name: 'Wichita', state: 'Kansas', stateAbbr: 'KS' },
  { slug: 'overland-park-ks', name: 'Overland Park', state: 'Kansas', stateAbbr: 'KS' },
  { slug: 'topeka-ks', name: 'Topeka', state: 'Kansas', stateAbbr: 'KS' },
  // Texas
  { slug: 'houston-tx', name: 'Houston', state: 'Texas', stateAbbr: 'TX', population: '2.3M' },
  { slug: 'dallas-tx', name: 'Dallas', state: 'Texas', stateAbbr: 'TX', population: '1.3M' },
  { slug: 'austin-tx', name: 'Austin', state: 'Texas', stateAbbr: 'TX', population: '961K' },
  { slug: 'san-antonio-tx', name: 'San Antonio', state: 'Texas', stateAbbr: 'TX', population: '1.4M' },
  { slug: 'fort-worth-tx', name: 'Fort Worth', state: 'Texas', stateAbbr: 'TX', population: '918K' },
  { slug: 'el-paso-tx', name: 'El Paso', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'arlington-tx', name: 'Arlington', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'plano-tx', name: 'Plano', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'corpus-christi-tx', name: 'Corpus Christi', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'lubbock-tx', name: 'Lubbock', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'laredo-tx', name: 'Laredo', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'irving-tx', name: 'Irving', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'garland-tx', name: 'Garland', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'frisco-tx', name: 'Frisco', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'mckinney-tx', name: 'McKinney', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'amarillo-tx', name: 'Amarillo', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'grand-prairie-tx', name: 'Grand Prairie', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'brownsville-tx', name: 'Brownsville', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'pasadena-tx', name: 'Pasadena', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'mesquite-tx', name: 'Mesquite', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'killeen-tx', name: 'Killeen', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'waco-tx', name: 'Waco', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'mcallen-tx', name: 'McAllen', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'midland-tx', name: 'Midland', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'odessa-tx', name: 'Odessa', state: 'Texas', stateAbbr: 'TX' },
  // Southwest & Mountain
  { slug: 'phoenix-az', name: 'Phoenix', state: 'Arizona', stateAbbr: 'AZ', population: '1.6M' },
  { slug: 'tucson-az', name: 'Tucson', state: 'Arizona', stateAbbr: 'AZ' },
  { slug: 'scottsdale-az', name: 'Scottsdale', state: 'Arizona', stateAbbr: 'AZ' },
  { slug: 'mesa-az', name: 'Mesa', state: 'Arizona', stateAbbr: 'AZ' },
  { slug: 'chandler-az', name: 'Chandler', state: 'Arizona', stateAbbr: 'AZ' },
  { slug: 'tempe-az', name: 'Tempe', state: 'Arizona', stateAbbr: 'AZ' },
  { slug: 'gilbert-az', name: 'Gilbert', state: 'Arizona', stateAbbr: 'AZ' },
  { slug: 'glendale-az', name: 'Glendale', state: 'Arizona', stateAbbr: 'AZ' },
  { slug: 'peoria-az', name: 'Peoria', state: 'Arizona', stateAbbr: 'AZ' },
  { slug: 'surprise-az', name: 'Surprise', state: 'Arizona', stateAbbr: 'AZ' },
  { slug: 'las-vegas-nv', name: 'Las Vegas', state: 'Nevada', stateAbbr: 'NV', population: '641K' },
  { slug: 'henderson-nv', name: 'Henderson', state: 'Nevada', stateAbbr: 'NV' },
  { slug: 'reno-nv', name: 'Reno', state: 'Nevada', stateAbbr: 'NV' },
  { slug: 'north-las-vegas-nv', name: 'North Las Vegas', state: 'Nevada', stateAbbr: 'NV' },
  { slug: 'sparks-nv', name: 'Sparks', state: 'Nevada', stateAbbr: 'NV' },
  { slug: 'albuquerque-nm', name: 'Albuquerque', state: 'New Mexico', stateAbbr: 'NM' },
  { slug: 'santa-fe-nm', name: 'Santa Fe', state: 'New Mexico', stateAbbr: 'NM' },
  { slug: 'las-cruces-nm', name: 'Las Cruces', state: 'New Mexico', stateAbbr: 'NM' },
  { slug: 'denver-co', name: 'Denver', state: 'Colorado', stateAbbr: 'CO', population: '715K' },
  { slug: 'colorado-springs-co', name: 'Colorado Springs', state: 'Colorado', stateAbbr: 'CO' },
  { slug: 'aurora-co', name: 'Aurora', state: 'Colorado', stateAbbr: 'CO' },
  { slug: 'fort-collins-co', name: 'Fort Collins', state: 'Colorado', stateAbbr: 'CO' },
  { slug: 'lakewood-co', name: 'Lakewood', state: 'Colorado', stateAbbr: 'CO' },
  { slug: 'thornton-co', name: 'Thornton', state: 'Colorado', stateAbbr: 'CO' },
  { slug: 'pueblo-co', name: 'Pueblo', state: 'Colorado', stateAbbr: 'CO' },
  { slug: 'salt-lake-city-ut', name: 'Salt Lake City', state: 'Utah', stateAbbr: 'UT', population: '200K' },
  { slug: 'west-valley-city-ut', name: 'West Valley City', state: 'Utah', stateAbbr: 'UT' },
  { slug: 'provo-ut', name: 'Provo', state: 'Utah', stateAbbr: 'UT' },
  { slug: 'west-jordan-ut', name: 'West Jordan', state: 'Utah', stateAbbr: 'UT' },
  { slug: 'orem-ut', name: 'Orem', state: 'Utah', stateAbbr: 'UT' },
  { slug: 'ogden-ut', name: 'Ogden', state: 'Utah', stateAbbr: 'UT' },
  { slug: 'boise-id', name: 'Boise', state: 'Idaho', stateAbbr: 'ID' },
  { slug: 'nampa-id', name: 'Nampa', state: 'Idaho', stateAbbr: 'ID' },
  { slug: 'meridian-id', name: 'Meridian', state: 'Idaho', stateAbbr: 'ID' },
  { slug: 'cheyenne-wy', name: 'Cheyenne', state: 'Wyoming', stateAbbr: 'WY' },
  { slug: 'casper-wy', name: 'Casper', state: 'Wyoming', stateAbbr: 'WY' },
  // West Coast
  { slug: 'los-angeles-ca', name: 'Los Angeles', state: 'California', stateAbbr: 'CA', population: '3.9M' },
  { slug: 'san-diego-ca', name: 'San Diego', state: 'California', stateAbbr: 'CA', population: '1.4M' },
  { slug: 'san-francisco-ca', name: 'San Francisco', state: 'California', stateAbbr: 'CA', population: '873K' },
  { slug: 'san-jose-ca', name: 'San Jose', state: 'California', stateAbbr: 'CA', population: '1.0M' },
  { slug: 'sacramento-ca', name: 'Sacramento', state: 'California', stateAbbr: 'CA', population: '524K' },
  { slug: 'fresno-ca', name: 'Fresno', state: 'California', stateAbbr: 'CA' },
  { slug: 'long-beach-ca', name: 'Long Beach', state: 'California', stateAbbr: 'CA' },
  { slug: 'oakland-ca', name: 'Oakland', state: 'California', stateAbbr: 'CA' },
  { slug: 'bakersfield-ca', name: 'Bakersfield', state: 'California', stateAbbr: 'CA' },
  { slug: 'anaheim-ca', name: 'Anaheim', state: 'California', stateAbbr: 'CA' },
  { slug: 'riverside-ca', name: 'Riverside', state: 'California', stateAbbr: 'CA' },
  { slug: 'stockton-ca', name: 'Stockton', state: 'California', stateAbbr: 'CA' },
  { slug: 'chula-vista-ca', name: 'Chula Vista', state: 'California', stateAbbr: 'CA' },
  { slug: 'irvine-ca', name: 'Irvine', state: 'California', stateAbbr: 'CA' },
  { slug: 'santa-ana-ca', name: 'Santa Ana', state: 'California', stateAbbr: 'CA' },
  { slug: 'san-bernardino-ca', name: 'San Bernardino', state: 'California', stateAbbr: 'CA' },
  { slug: 'modesto-ca', name: 'Modesto', state: 'California', stateAbbr: 'CA' },
  { slug: 'oxnard-ca', name: 'Oxnard', state: 'California', stateAbbr: 'CA' },
  { slug: 'fontana-ca', name: 'Fontana', state: 'California', stateAbbr: 'CA' },
  { slug: 'glendale-ca', name: 'Glendale', state: 'California', stateAbbr: 'CA' },
  { slug: 'moreno-valley-ca', name: 'Moreno Valley', state: 'California', stateAbbr: 'CA' },
  { slug: 'huntington-beach-ca', name: 'Huntington Beach', state: 'California', stateAbbr: 'CA' },
  { slug: 'santa-clarita-ca', name: 'Santa Clarita', state: 'California', stateAbbr: 'CA' },
  { slug: 'garden-grove-ca', name: 'Garden Grove', state: 'California', stateAbbr: 'CA' },
  { slug: 'oceanside-ca', name: 'Oceanside', state: 'California', stateAbbr: 'CA' },
  { slug: 'ontario-ca', name: 'Ontario', state: 'California', stateAbbr: 'CA' },
  { slug: 'elk-grove-ca', name: 'Elk Grove', state: 'California', stateAbbr: 'CA' },
  { slug: 'corona-ca', name: 'Corona', state: 'California', stateAbbr: 'CA' },
  { slug: 'salinas-ca', name: 'Salinas', state: 'California', stateAbbr: 'CA' },
  { slug: 'palmdale-ca', name: 'Palmdale', state: 'California', stateAbbr: 'CA' },
  { slug: 'pomona-ca', name: 'Pomona', state: 'California', stateAbbr: 'CA' },
  { slug: 'escondido-ca', name: 'Escondido', state: 'California', stateAbbr: 'CA' },
  { slug: 'torrance-ca', name: 'Torrance', state: 'California', stateAbbr: 'CA' },
  { slug: 'sunnyvale-ca', name: 'Sunnyvale', state: 'California', stateAbbr: 'CA' },
  { slug: 'pasadena-ca', name: 'Pasadena', state: 'California', stateAbbr: 'CA' },
  { slug: 'hayward-ca', name: 'Hayward', state: 'California', stateAbbr: 'CA' },
  { slug: 'santa-rosa-ca', name: 'Santa Rosa', state: 'California', stateAbbr: 'CA' },
  { slug: 'visalia-ca', name: 'Visalia', state: 'California', stateAbbr: 'CA' },
  { slug: 'concord-ca', name: 'Concord', state: 'California', stateAbbr: 'CA' },
  { slug: 'thousand-oaks-ca', name: 'Thousand Oaks', state: 'California', stateAbbr: 'CA' },
  { slug: 'simi-valley-ca', name: 'Simi Valley', state: 'California', stateAbbr: 'CA' },
  { slug: 'roseville-ca', name: 'Roseville', state: 'California', stateAbbr: 'CA' },
  { slug: 'petaluma-ca', name: 'Petaluma', state: 'California', stateAbbr: 'CA' },
  { slug: 'santa-barbara-ca', name: 'Santa Barbara', state: 'California', stateAbbr: 'CA' },
  { slug: 'seattle-wa', name: 'Seattle', state: 'Washington', stateAbbr: 'WA', population: '737K' },
  { slug: 'spokane-wa', name: 'Spokane', state: 'Washington', stateAbbr: 'WA' },
  { slug: 'tacoma-wa', name: 'Tacoma', state: 'Washington', stateAbbr: 'WA' },
  { slug: 'bellevue-wa', name: 'Bellevue', state: 'Washington', stateAbbr: 'WA' },
  { slug: 'kent-wa', name: 'Kent', state: 'Washington', stateAbbr: 'WA' },
  { slug: 'everett-wa', name: 'Everett', state: 'Washington', stateAbbr: 'WA' },
  { slug: 'renton-wa', name: 'Renton', state: 'Washington', stateAbbr: 'WA' },
  { slug: 'yakima-wa', name: 'Yakima', state: 'Washington', stateAbbr: 'WA' },
  { slug: 'portland-or', name: 'Portland', state: 'Oregon', stateAbbr: 'OR', population: '652K' },
  { slug: 'salem-or', name: 'Salem', state: 'Oregon', stateAbbr: 'OR' },
  { slug: 'eugene-or', name: 'Eugene', state: 'Oregon', stateAbbr: 'OR' },
  { slug: 'gresham-or', name: 'Gresham', state: 'Oregon', stateAbbr: 'OR' },
  { slug: 'hillsboro-or', name: 'Hillsboro', state: 'Oregon', stateAbbr: 'OR' },
  { slug: 'beaverton-or', name: 'Beaverton', state: 'Oregon', stateAbbr: 'OR' },
  { slug: 'bend-or', name: 'Bend', state: 'Oregon', stateAbbr: 'OR' },
  { slug: 'medford-or', name: 'Medford', state: 'Oregon', stateAbbr: 'OR' },
  // Pacific
  { slug: 'honolulu-hi', name: 'Honolulu', state: 'Hawaii', stateAbbr: 'HI' },
  { slug: 'anchorage-ak', name: 'Anchorage', state: 'Alaska', stateAbbr: 'AK' },
  { slug: 'fairbanks-ak', name: 'Fairbanks', state: 'Alaska', stateAbbr: 'AK' },
  // Additional metro areas
  { slug: 'oklahoma-city-ok', name: 'Oklahoma City', state: 'Oklahoma', stateAbbr: 'OK' },
  { slug: 'tulsa-ok', name: 'Tulsa', state: 'Oklahoma', stateAbbr: 'OK' },
  { slug: 'norman-ok', name: 'Norman', state: 'Oklahoma', stateAbbr: 'OK' },
  { slug: 'broken-arrow-ok', name: 'Broken Arrow', state: 'Oklahoma', stateAbbr: 'OK' },
  { slug: 'lawton-ok', name: 'Lawton', state: 'Oklahoma', stateAbbr: 'OK' },
  { slug: 'columbia-md', name: 'Columbia', state: 'Maryland', stateAbbr: 'MD' },
  { slug: 'cape-town-sc', name: 'North Charleston', state: 'South Carolina', stateAbbr: 'SC' },
  { slug: 'myrtle-beach-sc', name: 'Myrtle Beach', state: 'South Carolina', stateAbbr: 'SC' },
  { slug: 'spartanburg-sc', name: 'Spartanburg', state: 'South Carolina', stateAbbr: 'SC' },
  { slug: 'frederick-md', name: 'Frederick', state: 'Maryland', stateAbbr: 'MD' },
  { slug: 'gaithersburg-md', name: 'Gaithersburg', state: 'Maryland', stateAbbr: 'MD' },
  { slug: 'boca-raton-fl', name: 'Boca Raton', state: 'Florida', stateAbbr: 'FL' },
  { slug: 'clearwater-fl', name: 'Clearwater', state: 'Florida', stateAbbr: 'FL' },
  { slug: 'pompano-beach-fl', name: 'Pompano Beach', state: 'Florida', stateAbbr: 'FL' },
  { slug: 'palm-bay-fl', name: 'Palm Bay', state: 'Florida', stateAbbr: 'FL' },
  { slug: 'miramar-fl', name: 'Miramar', state: 'Florida', stateAbbr: 'FL' },
  { slug: 'lakeland-fl', name: 'Lakeland', state: 'Florida', stateAbbr: 'FL' },
  { slug: 'denton-tx', name: 'Denton', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'carrollton-tx', name: 'Carrollton', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'round-rock-tx', name: 'Round Rock', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'beaumont-tx', name: 'Beaumont', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'abilene-tx', name: 'Abilene', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'pearland-tx', name: 'Pearland', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'richardson-tx', name: 'Richardson', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'lewisville-tx', name: 'Lewisville', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'cedar-park-tx', name: 'Cedar Park', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'san-angelo-tx', name: 'San Angelo', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'tyler-tx', name: 'Tyler', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'allen-tx', name: 'Allen', state: 'Texas', stateAbbr: 'TX' },
  { slug: 'arvada-co', name: 'Arvada', state: 'Colorado', stateAbbr: 'CO' },
  { slug: 'westminster-co', name: 'Westminster', state: 'Colorado', stateAbbr: 'CO' },
  { slug: 'centennial-co', name: 'Centennial', state: 'Colorado', stateAbbr: 'CO' },
  { slug: 'highlands-ranch-co', name: 'Highlands Ranch', state: 'Colorado', stateAbbr: 'CO' },
  { slug: 'greeley-co', name: 'Greeley', state: 'Colorado', stateAbbr: 'CO' },
  { slug: 'murfreesboro-tn', name: 'Murfreesboro', state: 'Tennessee', stateAbbr: 'TN' },
  { slug: 'jackson-tn', name: 'Jackson', state: 'Tennessee', stateAbbr: 'TN' },
  { slug: 'independence-mo', name: 'Independence', state: 'Missouri', stateAbbr: 'MO' },
];

// Cities used for static generation only. A staging build renders a small
// sample instead of the full cross-product: 15 city routes x 305 cities is
// over 13,000 pages, which will not build on a small box. Unlisted cities
// still render on demand, so staging loses no functionality.
export const staticParamCities: City[] =
  process.env.NEXT_PUBLIC_SITE_ENV === 'staging' ? cities.slice(0, 6) : cities;


// ─── Helpers ─────────────────────────────────────────────────────────────────

export function getCityBySlug(slug: string): City | undefined {
  return cities.find((c) => c.slug === slug);
}

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}

export function getIndustryBySlug(slug: string): Industry | undefined {
  return industries.find((i) => i.slug === slug);
}

export function formatCityState(city: City): string {
  return `${city.name}, ${city.stateAbbr}`;
}
